from random import *
"""
    规则：
    全局变量大写字母表示：如 URL

"""
UESRNAME='//*[@id="app"]/div/div[2]/div/div/div/div[1]/div[2]/div/div[2]/div[2]/div[1]/form/div[1]/div/div/input'
PASSWORD='//*[@id="app"]/div/div[2]/div/div/div/div[1]/div[2]/div/div[2]/div[2]/div[1]/form/div[2]/div/div/input'
CHECKBOX='//*[@id="app"]/div/div[2]/div/div/div/div[1]/div[2]/div/div[2]/div[2]/div[1]/form/div[3]/label/span/span'
X='//*[@id="app"]/div/div[2]/div/div[2]/div/div[2]/div/div[1]/button/i'
SCALE='//*[@id="app"]/div/div[2]/div/div[2]/div/div[1]/div/div[2]/div/div'
Start_the_topic='//*[@id="app"]/div/div[2]/div/div[1]/div/div/div/div/div[3]/div[1]/button'
NEXT='//*[@id="app"]/div/div[2]/div[1]/div/div/div/div/button'
Enter_the_assessment='//*[@id="app"]/div/div[2]/div[1]/div/div/div/div/button'
Very_much='//*[@id="app"]/div/div[2]/div/div[1]/div/div/div/div/div[3]/button[5]'
relatively_match='//*[@id="app"]/div/div[2]/div/div[1]/div/div/div/div/div[3]/button[4]'
indeterminacy='//*[@id="app"]/div/div[2]/div/div[1]/div/div/div/div/div[3]/button[3]'
Comparative_incompatibility='//*[@id="app"]/div/div[2]/div/div[1]/div/div/div/div/div[3]/button[2]'
Very_out_of_line='//*[@id="app"]/div/div[2]/div/div[1]/div/div/div/div/div[3]/button[1]'
# status_num_play='//*[@id="app"]/div/div[2]/div[1]/div/div/div/div/div[2]/div[2]/div/span[1]'
# status_num_total='//*[@id="app"]/div/div[2]/div[1]/div/div/div/div/div[2]/div[2]/div/span[3]'
status_num_play='//span[@class="status-num-play"]'
status_num_total='//span[@class="status-num-total"]'
NEW_PASSWORD='//*[@id="app"]/div/div[2]/div/div[2]/div/div[2]/div/div[1]/span'
publicKey='pvj9bTwwaY4YdPiwRBH5RE25o9ZM8BHG'
PORD_URL='https://hapi.6noblexc.com'
DEV_URL='http://jupiter.6noble.net:8098'
REPORT_TEXT='//*[@id="app"]/div/div[2]/div[1]/div/div/div/div[1]/div/div[2]/p'
check_report='//*[@id="pane-complete"]/div/div[1]/div/div[3]/div[2]/button'
grade_four='//span[text()="四年级"]'
grade_five='//span[text()="五年级"]'
grade_six='//span[text()="六年级"]'
student_cadre='//span[text()="学生干部"]'
no_student_cadre='//span[text()="非学生干部"]'
resident_student= '//span[text()="住校生"]'
no_resident_student= '//span[text()="非住校生"]'
only_child='//span[text()="独生子女"]'
no_only_child='//span[text()="非独生子女"]'
years_of_working_1='//span[text()="1年以下（含1年）"]'
years_of_working_2='//span[text()="1-3年（含3年）"]'
years_of_working_3='//span[text()="3-5年（含5年）"]'
years_of_working_4='//span[text()="5-10年（含10年）"]'
years_of_working_5='//span[text()="10-20年（含20年）"]'
years_of_working_6='//span[text()="20年以上"]'
Rank_1='//span[text()="特级教师"]'
Rank_7='//span[text()="正高级教师"]'
Rank_2='//span[text()="高级教师"]'
Rank_3='//span[text()="一级教师"]'
Rank_4='//span[text()="二级教师"]'
Rank_5='//span[text()="三级教师"]'
Rank_6='/html/body/div[8]/div[1]/div[1]/ul/li[7]'
job_1='//span[text()="管理岗"]'
job_2='//span[text()="一线教职工"]'
job_3='/html/body/div[8]/div[1]/div[1]/ul/li[3]'
Nature_1='//span[text()="事业编制"]'
Nature_2='//span[text()="合同制"]'
Nature_3='/html/body/div[8]/div[1]/div[1]/ul/li[3]'
marriage_1='//span[text()="已婚"]'
marriage_2='//span[text()="未婚"]'
marriage_3='//span[text()="离异"]'
marriage_4='//span[text()="丧偶"]'
sex1='//span[text()="男"]'
sex2='//span[text()="女"]'
age1='//span[text()="28周岁及以下"]'
age2='//span[text()="29-35周岁（含）"]'
age3='//span[text()="36-50周岁（含）"]'
age4='//span[text()="51周岁及以上"]'
education5='//span[text()="初中以下"]'
education1='//span[text()="初中"]'
education2='//span[text()="中职"]'
education3='//span[text()="高中"]'
education4='//span[text()="高职"]'
education6='//span[text()="大专"]'
education7='//span[text()="本科"]'
education8='//span[text()="硕士"]'
education9='//span[text()="博士"]'
education10='//*[@id="app"]/div/div[1]/div/div/div[2]/div/div[1]/form/div[3]/div[3]/div/div[2]/div[1]/ul/li[10]/div'